# Site settings
title: William Harvey Design
email: william.jm.harvey@gmail.com
description: "A collection of works designed by William Harvey"
info: "Edit this info in _config.yml"
message: "Edit this message in _config.yml"
keywords: "mac,apple,iphone,ios,osx,games,apps,development"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.william-harvey.djwldo.com" # the base hostname & protocol for your site
twitter_username: WLDO
# Build settings
markdown: kramdown
author:
    name: William Harvey
    twitter: WLDO
    url: http://www.william-harvey.djwldo.com
    header_bg: /images/profile-header.png
    avatar: /images/avatar.jpg
    email: william.jm.harvey@gmail.com
facebook:
    image: /images/delightfuldev-facebook-cover.png
